### ISSUE TITLE
"Stream length must be non-negative and less than 2^31 - 1 - origin. (Parameter 'offset')" error when unpacking vromfs

### ISSUE THREAD

**Issue by AidenTKZ** [Keksilton/WtTools#3]
Hi, upon unpacking vromfses such as : atlases.vromfs.bin, images.vromfs.bin, tex.vromfs.bin....etc this error appears

![image](https://user-images.githubusercontent.com/68249440/175837067-48a91806-7b74-4d86-a9f3-0e62f98b34f6.png)

**Comment by Keksilton** [comment]
Thanks for reporting! I will take a look later today.

**Comment by Keksilton** [comment]
@AidenTKZ It looks like it's either new or yet unsupported format. I will work on implementing support for it, but I have little to no free time at the moment. This might take some time 😞

**Comment by Keksilton** [comment]
This one was a bug. I was deobfuscating files that are not obfuscated... :)
So that is fixed now and is available with new release https://github.com/Keksilton/WtTools/releases/tag/v0.1.7.2-alpha
