### ISSUE TITLE
"Index was outside the bounds of the array." error upon unpacking game.vromfs.bin and lang.vromfs.bin

### ISSUE THREAD

**Issue by AidenTKZ** [Keksilton/WtTools#4]
Hi, upon unpacking game.vromfs.bin and lang.vromfs.bin, this error gets raised :

![image](https://user-images.githubusercontent.com/68249440/176000843-dded821e-de6a-4dc6-9308-c11d01c411d8.png)
![image](https://user-images.githubusercontent.com/68249440/176000855-1bf6c567-058c-4c56-be03-137f119ac5ca.png)

**Comment by Keksilton** [comment]
I was unable to find the source of the problem yet, but I added ability to continue unpacking if some of the files have caused an exception. Available in latest release.
I will keep this ticket open until there is an actual solution.

**Comment by Keksilton** [comment]
I have resolved this error. The fix is available in the latest release. https://github.com/Keksilton/WtTools/releases/tag/v0.1.8-alpha
