### ISSUE TITLE
"Unable to read beyond the end of the stream." error upon unpacking Regional.vromfs.bin

### ISSUE THREAD

**Issue by AidenTKZ** [Keksilton/WtTools#5]
Hi, when unpacking Regional.vromfs.bin, this error gets raised :

![image](https://user-images.githubusercontent.com/68249440/176001231-e46ab8cc-b96c-474d-a78f-92afcb157120.png)

**Comment by Keksilton** [comment]
I believe this is a duplicate of Issue #4.

**Comment by Keksilton** [comment]
This was not a duplicate, but I was able to resolve this issue with the latest release.
