### ISSUE TITLE
Strange/random output on some Blks from Regional.vromfs.bin

### ISSUE THREAD

**Issue by AidenTKZ** [Keksilton/WtTools#6]
Hi, upon unpacking Regional.vromfs.bin blks, downloadable_decals.blkx and downloadable_skins.blkx show strange random outputs. 

left side is how it should be, right side is what it is currently showing

![image](https://user-images.githubusercontent.com/68249440/177144442-d2131cf2-e4fc-49f5-b39e-616fe4d6109e.png)

**Comment by Keksilton** [comment]
Is the right side just an older file or is it the same file unpacked using an ok there tool? If so - what tool?

I will also try to add test cases so this doesn't happen in the future

**Comment by AidenTKZ** [comment]
it is the same version (2.17.0.50 for both), left was done with kotiq's tools, right with yours

**Comment by Keksilton** [comment]
I will check out his implementation, so should be able to publish a fix
this week

**Comment by Keksilton** [comment]
Found the issue. Didn't have correct processing for one of the bit flags. 
Fixed in the latest release. Hopefully everything else is working properly. 
Please let me know if it doesn't.

Thank you for your report <3
