### ISSUE TITLE
Unhandled exception

### ISSUE THREAD

**Issue by CrIcKeT98** [Keksilton/WtTools#7]
After compiling and running your project via command line I have a error:
![image](https://user-images.githubusercontent.com/33666353/184548418-c2786318-795a-4682-bec4-ef09440da516.png)

**Comment by CrIcKeT98** [comment]
My bad, Unpacker not intended for separate decryption of blk files.

**Comment by Keksilton** [comment]
At least the way I remember it, it should be able to, let me check first

**Comment by CrIcKeT98** [comment]
My mistake was that i was trying to decrypt the blk file. Obviously, the Unpacker is designed to unpack bin files and decrypts the blk files immediately.

**Comment by Keksilton** [comment]
@CrIcKeT98 It should be able to unpack individual blk files, assuming they were not previously inside of bin. Some data necessary for unpacking is included with the bin file, but not individual BLKs

**Comment by CrIcKeT98** [comment]
I'm trying load unpacked mission in missioned editor, but the file doesn't seem to load. What is the problem?

**Comment by Keksilton** [comment]
It's being unpacked to JSON format which is different from native BLK format. Currently I only support unpacking to JSON.

**Comment by CrIcKeT98** [comment]
Ok, I'll write own decryptor because the original wt-tools don't work. Thanks.

**Comment by Keksilton** [comment]
I have created another ticket to add support for "strict", which is one the human readable Blk format.. I will implement it when I get free time, but it's hard to promise a deadline. 

Feel free to create a pull request if you end up implementing it.

**Comment by CrIcKeT98** [comment]
Unfortunately I don't know C#. I can write a public blk decryptor in C++ and compile a DLL that you can use.
